<?php

return [
    'APP_ENV' => 'production',
    'APP_BASE_URL' => 'https://webtest.solutions',
    'DB_HOST' => '127.0.0.1',
    'DB_PORT' => 3306,
    'DB_NAME' => 'bug_catcher',
    'DB_USER' => 'bugcatcher_app',
    'DB_PASS' => 'replace-with-a-strong-random-password',
    'UPLOADS_DIR' => '/var/www/bugcatcher/shared/uploads/issues',
    'UPLOADS_URL' => 'uploads/issues',
    'CHECKLIST_UPLOADS_DIR' => '/var/www/bugcatcher/shared/uploads/checklists',
    'CHECKLIST_UPLOADS_URL' => 'uploads/checklists',
    'CHECKLIST_BOT_SHARED_SECRET' => 'replace-with-a-long-random-secret',
    'OPENCLAW_INTERNAL_SHARED_SECRET' => 'replace-with-a-second-long-random-secret',
    'OPENCLAW_ENCRYPTION_KEY' => 'replace-with-a-32-byte-secret',
    'OPENCLAW_TEMP_UPLOAD_DIR' => '/var/www/bugcatcher/shared/uploads/openclaw-tmp',
    'OPENCLAW_LOG_LEVEL' => 'info',
    'MAIL_MAILER' => 'smtp',
    'MAIL_HOST' => 'smtp.gmail.com',
    'MAIL_PORT' => 587,
    'MAIL_USERNAME' => 'smtp-user@example.com',
    'MAIL_PASSWORD' => '',
    'MAIL_ENCRYPTION' => 'tls',
    'MAIL_FROM_ADDRESS' => 'no-reply@example.com',
    'MAIL_FROM_EMAIL' => 'no-reply@example.com',
    'MAIL_FROM_NAME' => 'WebTest',
    'PASSWORD_RESET_OTP_TTL_SECONDS' => 600,
    'PASSWORD_RESET_RESEND_COOLDOWN_SECONDS' => 60,
    'PASSWORD_RESET_MAX_VERIFY_ATTEMPTS' => 5,
    'PASSWORD_RESET_MAX_RESENDS' => 3,
];
